### ISSUE TITLE
Plans for clickable bar

### ISSUE THREAD

**Issue by BramVerb** [Stargarth/Goblocks#4]
I was wondering if you have any plans for adding support for signaling clicks to blocks and running a definable command when that happens.
I know this would also involve a patch for dwm, but I think this could be a very neat feature.

Also: I don't mind helping with it, but I also wanted to verify whether this is something you want in Goblocks?

**Comment by BramVerb** [comment]
No idea how this might be implemented yet, because it requires sending the position in the bar that was clicked.

**Comment by Ldaxar** [comment]
Hey @BramVerb !

I wasn't planning for it as I don't use this functionality, but I think that it should be possible to do without changes to goblocks.

I [looked around](https://github.com/LukeSmithxyz/dwm/blob/master/config.h) in builds that have a clickable bar and it seems that every time when block is clicked, dwm is launching a function e.g:
```
/* button definitions */
/* click can be ClkTagBar, ClkLtSymbol, ClkStatusText, ClkWinTitle, ClkClientWin, or ClkRootWin */
static Button buttons[] = {
	/* click                event mask      button          function        argument */
	{ ClkWinTitle,          0,              Button2,        zoom,           {0} },
	{ ClkStatusText,        0,              Button1,        sigdwmblocks,   {.i = 1} },
	{ ClkStatusText,        0,              Button2,        sigdwmblocks,   {.i = 2} },
	{ ClkStatusText,        0,              Button3,        sigdwmblocks,   {.i = 3} },
	{ ClkStatusText,        0,              Button4,        sigdwmblocks,   {.i = 4} },
	{ ClkStatusText,        0,              Button5,        sigdwmblocks,   {.i = 5} },
	{ ClkStatusText,        ShiftMask,      Button1,        sigdwmblocks,   {.i = 6} },
	{ ClkStatusText,        ShiftMask,      Button3,        spawn,          SHCMD("st -e nvim ~/.local/src/dwmblocks/config.h") },
	{ ClkClientWin,         MODKEY,         Button1,        movemouse,      {0} },
	{ ClkClientWin,         MODKEY,         Button2,        defaultgaps,	{0} },
	{ ClkClientWin,         MODKEY,         Button3,        resizemouse,    {0} },
	{ ClkClientWin,		MODKEY,		Button4,	incrgaps,	{.i = +1} },
	{ ClkClientWin,		MODKEY,		Button5,	incrgaps,	{.i = -1} },
	{ ClkTagBar,            0,              Button1,        view,           {0} },
	{ ClkTagBar,            0,              Button3,        toggleview,     {0} },
	{ ClkTagBar,            MODKEY,         Button1,        tag,            {0} },
	{ ClkTagBar,            MODKEY,         Button3,        toggletag,      {0} },
	{ ClkTagBar,		0,		Button4,	shiftview,	{.i = -1} },
	{ ClkTagBar,		0,		Button5,	shiftview,	{.i = 1} },
	{ ClkRootWin,		0,		Button2,	togglebar,	{0} },
};
```
sigdwmblocks is just a patched function in dwm:
```
void
sigdwmblocks(const Arg *arg)
{
	union sigval sv;
	sv.sival_int = 0 | (dwmblockssig << 8) | arg->i;
	if (!dwmblockspid)
		if (getdwmblockspid() == -1)
			return;

	if (sigqueue(dwmblockspid, SIGUSR1, sv) == -1) {
		if (errno == ESRCH) {
			if (!getdwmblockspid())
				sigqueue(dwmblockspid, SIGUSR1, sv);
		}
	}
}
```
I think that one solution could be to create a new patch for dwm (e.g. siggoblocks) that sends a corresponding signal (e.g. 39) to new application (e.g. gowatch)  which will run corresponding functionality.

This new program could read goblocks.json config file and use it to map signal sent by dwm to appropriate command. Naturally it would require some additional data in goblocks.json e.g:
```
{
			"updateSignal": "39",
			"command": "(sleep 5 ; curl \"wttr.in\/London?format=3\")",
		        "onClick":"termite --hold -e 'curl wttr.in'",
			"timer": "45m"
},
```
It sounds a little convoluted but:
1.  This keeps goblocks true to UNIX philosophy as it's doing one thing only and it's doing it well.
2. Implementation of this 2nd program should be trivial.
3. No need to juggle patches around/ keep code that is redundant for people that don't use it.

If you want to give dwm patch a go(pun not intended), I can write click listening application (it's basically readConfig() method + scan of actions array to find clickable blocks and make new map out of them).

Let me know your thoughts :P.

**Comment by BramVerb** [comment]
Hi @Stargarth 
Thanks for taking the time to  providing an extensive response!

All in all, I think your proposal looks very promising.
A seperate program indeeds seems like a better plan and makes it easier to send the same signal numbers to.
I am still thinking about how dwm could distinguish between which block is pressed. It would for example require it to split on the blocks seperator, and then also read the blocks config to get the suitable signal to send.  I haven't found a dwm patch that uses the clicked location inside the status text for running some function. I am sure this isn't a major thing to solve, but it would require some research.

Upon writing this, I also rethought of the added value of such a clickable status bar. Although I wouldn't mind giving this a go (sorry had to do it too), as of now I don't think the usefulnes is enough of an incentive to do it right now, maybe at a later point in time I will give it a try. 

Thanks again for your response and also for the work you have done on goblocks.

**Comment by Ldaxar** [comment]
No worries, I'm glad that you enjoy goblocks!
I'm closing down this issue but don't hesitate to open a new one if you want to pick up this discussion again :) .
